# GainExpDisplay Configuration

# Display text when gaining experience
gain-xp:
  enabled: true
  message: '<green><bold>Gain XP: <yellow><bold>+%amount%'

# Display text when repairing items with Mending
mending-repair:
  enabled: true
  message: '<aqua><bold>Mending Repair: <yellow><bold>+%amount% <green>(%durability%/%max%)'