name: GainExpDisplay
version: 2.1.0
main: dev.punjarrr.gainExpDisplay.GainExpDisplay
api-version: 1.17
authors: [PunJarrr]
description: Displays XP gain and Mending repair progress directly in your action bar.
commands:
  gainexpdisplay:
    description: Main command
    usage: /ged reload
    aliases: [ged]
permissions:
  gainexpdisplay.reload:
    description: Allows reloading the plugin.
    default: op
  gainexpdisplay.gainexp:
    description: Display text when gaining experience.
    default: true
  gainexpdisplay.mending:
    description: Display text when repairing items with Mending.
    default: true